default:
  image:
    name: ghcr.io/opentofu/opentofu:1.10.6
    entrypoint: [""]
  tags:
    - tf

stages:
  - validate
  - plan

validate:
  stage: validate 
  script:
    - tofu fmt -check -recursive -diff
    - tofu init -backend=false
    - tofu validate

plan:
  stage: plan
  script:
    - |
      echo "FQDN=$STAND_FQDN OS=$STAND_OS RAM=$STAND_RAM"
      HOST="${STAND_FQDN%%.*}"
      ZONE="${STAND_FQDN#*.}"
      echo "$HOST | $ZONE"
  rules:
    - if: $STAND_FQDN == "" || $STAND_OS == "" || $STAND_RAM == ""
      when: never
    - if: $CI_PIPELINE_SOURCE == "api"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "web"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - when: never
