default:
  image:
    name: ghcr.io/opentofu/opentofu:1.10.6
    entrypoint: [""]
  tags:
    - tf

.tf_backend: &tf_backend |  
  export TF_VAR_pve_token="$PROXMOX_VE_API_TOKEN"
  export TF_HTTP_USERNAME="gitlab-ci-token"
  export TF_HTTP_PASSWORD="${CI_JOB_TOKEN}"
  export TF_HTTP_ADDRESS="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/stand-${HOST}"
  export TF_HTTP_LOCK_ADDRESS="${TF_HTTP_ADDRESS}/lock"
  export TF_HTTP_UNLOCK_ADDRESS="${TF_HTTP_ADDRESS}/lock"
  export TF_HTTP_LOCK_METHOD=POST
  export TF_HTTP_UNLOCK_METHOD=DELETE
  export TF_VAR_password_hash="$(printf '%s' "$STAND_PASSWORD_HASH_B64" | base64 -d | tr -d '\n')"

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate 
  script:
    - tofu fmt -check -recursive -diff
    - tofu init -backend=false
    - tofu validate

plan:
  stage: plan
  script:
    - |
      for v in STAND_FQDN STAND_OS STAND_MEMORY STAND_DISK STAND_CORES; do
        eval "val=\$$v"
        [ -n "$val" ] || { echo "Не задана обязательная переменная $v"; exit 1; }
      done

      HOST="${STAND_FQDN%%.*}"
      ZONE="${STAND_FQDN#*.}"
      if [ "$HOST" = "$ZONE" ]; then
        echo "STAND_FQDN должен быть FQDN: $STAND_FQDN"
        exit 1
      fi

      if ! echo "$STAND_MEMORY" | grep -Eq '^[0-9]+$'; then
        echo "STAND_MEMORY задан не как число: $STAND_MEMORY"
        exit 1
      fi

      if ! echo "$STAND_CORES" | grep -Eq '^[0-9]+$'; then
        echo "STAND_CORES задан не как число: $STAND_CORES"
        exit 1
      fi

      if ! echo "$STAND_DISK" | grep -Eq '^[0-9]+$'; then
        echo "STAND_DISK задан не как число: $STAND_DISK"
        exit 1
      fi

      if [ "$STAND_MEMORY" -gt 50 ]; then 
        echo "Чрезмерное выделение RAM: $STAND_MEMORY > 50"
        exit 1
      fi

      case "$STAND_OS" in 
        redos|astra)
        ;;
        *)
        echo "STAND_OS задан неверно: $STAND_OS. Варианты: astra | redos"
        exit 1
        ;;
      esac

      PVE_API="https://10.205.251.3:8006/api2/json"
      VMID=""

      for id in $(seq 302 350); do
        if  wget -qO /dev/null --no-check-certificate \
              --header="Authorization: PVEAPIToken=$PROXMOX_VE_API_TOKEN" \
              "$PVE_API/cluster/nextid?vmid=$id"; then
            VMID="$id"
            break;
        fi
      done

      if [ -z "$VMID" ]; then
        echo "Нет свободных VMID в диапазоне"
        exit 1
      fi
      echo "$VMID"      
      echo "$HOST | $ZONE"

      EXTRA=""
      [ -n "${STAND_NODE_NAME}" ] && EXTRA="${EXTRA} node_name = \"${STAND_NODE_NAME}\"
      "
      [ -n "${STAND_POOL_ID}" ] && EXTRA="${EXTRA} pool_id = \"${STAND_POOL_ID}\"
      "
      [ -n "${STAND_IP}" ] && EXTRA="${EXTRA} ip = \"${STAND_IP}\"
      "
      [ -n "${STAND_GATEWAY}" ] && EXTRA="${EXTRA} gateway = \"${STAND_GATEWAY}\"
      "
      [ -n "${STAND_VLAN_ID}" ] && EXTRA="${EXTRA} vlan_id = ${STAND_VLAN_ID}
      "
      [ -n "${STAND_MAC_ADDRESS}" ] && EXTRA="${EXTRA} mac_address = \"${STAND_MAC_ADDRESS}\"
      "
      [ -n "${STAND_CORES}" ] && EXTRA="${EXTRA} cores = ${STAND_CORES}
      "
      [ -n "${STAND_MEMORY}" ] && EXTRA="${EXTRA} memory = $(( STAND_MEMORY * 1024 ))
      "
      [ -n "${STAND_DISK}" ] && EXTRA="${EXTRA} disk = ${STAND_DISK}
      "
      [ -n "${STAND_ON_BOOT}" ] && EXTRA="${EXTRA} on_boot = ${STAND_ON_BOOT}
      "
      [ -n "${STAND_STARTED}" ] && EXTRA="${EXTRA} started = ${STAND_STARTED}
      "
      [ -n "${STAND_PROTECTION}" ] && EXTRA="${EXTRA} protection = ${STAND_PROTECTION}
      "
      [ -n "${STAND_BACKUP}" ] && EXTRA="${EXTRA} backup = ${STAND_BACKUP}
      "
      [ -n "${STAND_TAGS}" ] && EXTRA="${EXTRA} tags = ${STAND_TAGS}
      "
      [ -n "${STAND_DESCRIPTION}" ] && EXTRA="${EXTRA} description = \"${STAND_DESCRIPTION}\""
      
      cat  > pipeline.auto.tfvars <<EOF
      pve_endpoint = "https://10.205.251.3:8006/"
      node_name    = "pve03"
      pool_id      = "NONAME"
      
      vm_id_range    = [302, 349]
      template_vm_id = 351
      vms = {
        "${HOST}" = {
          vm_id = ${VMID}
          ${EXTRA}
        }
      }
      EOF

      ls -la
      cat pipeline.auto.tfvars

    - *tf_backend
    - tofu init
    - tofu plan -out=tfplan
    - tofu show -json tfplan > plan.json
    - tofu show -no-color tfplan

  artifacts:
    paths:
      - pipeline.auto.tfvars
      - tfplan
  rules:
    - if: '$STAND_FQDN && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "trigger")'
      when: on_success
    - when: never

apply:
  stage: apply
  needs: [plan]
  script:
    - |
      HOST="${STAND_FQDN%%.*}"
    - *tf_backend
    - tofu init
    - tofu apply -input=false tfplan
  rules:
    - if: '$STAND_FQDN && ($CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "trigger")'
      when: manual
